# Generated by Django 5.2.16 on 2026-07-23 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaggio', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('letta', models.BooleanField(default=False)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creato_il'],
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('spogliatoio', models.BooleanField(default=False)),
                ('numero_partecipanti', models.PositiveIntegerField(default=1)),
                ('stato', models.CharField(choices=[('confermata', 'Confermata'), ('cancellata', 'Cancellata')], default='confermata', max_length=12)),
                ('prezzo_listino', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prezzo_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('cancellata_il', models.DateTimeField(blank=True, null=True)),
                ('gestore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenotazioni_gestite', to=settings.AUTH_USER_MODEL)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-ora_inizio'],
            },
        ),
        migrations.CreateModel(
            name='ListaAttesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_attesa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creato_il'],
                'unique_together': {('utente', 'data', 'ora_inizio')},
            },
        ),
    ]
