# Generated by Django 5.2.16 on 2026-07-23 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Campo da Beach Volley', max_length=100)),
                ('descrizione', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrarioApertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno_settimana', models.IntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')], unique=True)),
                ('aperto', models.BooleanField(default=True)),
                ('ora_apertura', models.TimeField(default='08:00')),
                ('ora_chiusura', models.TimeField(default='23:00')),
            ],
            options={
                'ordering': ['giorno_settimana'],
            },
        ),
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.CharField(blank=True, max_length=255)),
                ('disponibile', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tariffa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_diurno_no_spogliatoio', models.DecimalField(decimal_places=2, default=12, max_digits=6)),
                ('prezzo_diurno_spogliatoio', models.DecimalField(decimal_places=2, default=18, max_digits=6)),
                ('prezzo_serale_no_spogliatoio', models.DecimalField(decimal_places=2, default=18, max_digits=6)),
                ('prezzo_serale_spogliatoio', models.DecimalField(decimal_places=2, default=24, max_digits=6)),
                ('soglia_partecipanti', models.PositiveIntegerField(default=8)),
                ('sovrapprezzo_persona_extra', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChiusuraStraordinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('ora_inizio', models.TimeField(blank=True, help_text='Vuoto = tutto il giorno', null=True)),
                ('ora_fine', models.TimeField(blank=True, help_text='Vuoto = tutto il giorno', null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiusure_create', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_inizio'],
            },
        ),
    ]
