# Generated by Django 5.2.16 on 2026-07-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orarioapertura',
            name='ora_chiusura',
            field=models.TimeField(default='00:00', help_text='00:00 = mezzanotte'),
        ),
    ]
